name: Test CI Workflow

on:
  workflow_call:

jobs: 
  validate_files: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Check if tsconfig.json exists 
        run: | 
          if [ ! -f tsconfig.json ]; then 
            echo "🚨 ERROR: tsconfig.json is missing. It is required for the build process."
            exit 1
          fi
        shell: bash 

  build_and_test:
    runs-on: ubuntu-latest 
    needs: validate_files 
    env:
      NODE_VERSION: 18 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: ${{ env.NODE_VERSION }} 
          cache: 'npm' 

      - name: Install dependencies
        run: npm install 

      - name: Run unit tests
        run: npm run test 

      - name: Build the application
        run: npm run build 

      - name: Copy package-json and prisma to dist
        run: npm run postbuild 

      - name: Upload Release Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact 
          path: dist/**