name: Test Quality Workflow

on:
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-latest 

    env:
      NODE_VERSION: 18

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: ${{ env.NODE_VERSION }} 
          cache: 'npm'         

      - name: Install dependencies
        run: npm install 

      - name: Build the application
        run: npm run build    

  # sonar_scan:
  #   runs-on: ubuntu-latest
  #   needs: build_and_test
  #   steps:
  #     - name: Run SonarQube analysis
  #       run: |
  #         npx sonar-scanner \
  #           -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
  #           -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
  #           -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
  #           -Dsonar.token=${{ secrets.SONAR_TOKEN }}
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}              

  sonar_scan:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Run SonarQube analysis
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=desafio-minsait \
            -Dsonar.organization=Minsait-Teste \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}                         